name: MyRPG
version: 1.0.0
main: dungnt.rpg.MyRPG
api-version: '1.21'

author: DungNT
description: Custom RPG Class and Skill System

commands:
  class:
    description: Quản lý Class RPG
    usage: /class

  skilltest:
    description: Sử dụng Skill RPG
    usage: /skilltest <skill>

  stattest:
    description: Test RPG stats

  mobtest:
    description: Spawn RPG test mob
    usage: /mobtest

  magicdamage:
    description: Test magic damage

  level:
    description: Xem Level và EXP
    usage: /level

  itemtest:
    description: Test RPG class items
    usage: /itemtest <warrior|mage|archer|assassin>

  equipment:
    description: Xem trang bị
    usage: /equipment

  itemstat:
    description: Thêm và xoá stat cho item đang cầm
    usage: /itemstat <add|remove|clear>

  team:
    description: Quản lý team
    usage: /team

  socket:
    description: Mở hệ thống socket
    usage: /socket

  itemsocket:
    description: Tạo và chỉnh sửa Gem
    usage: /itemsocket <name|special|addstat|lore|setlevel>
